spring:
  main:
    banner-mode: "off"
  application:
    name: project91
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: test
    password: test@123
  sql:
    init:
      mode: always
